### ISSUE TITLE
BeautifulSoup Parser

### ISSUE THREAD

**Issue by gbakes** [Destaq/reddit-wallpapers#1]
I followed the readme and got this error:

```
Navigated to directory...
Removed previous files...

Processing image 1 of 100.Traceback (most recent call last):
  File "add_images.py", line 48, in <module>
    soup = BeautifulSoup(html_page, "lxml")
  File "/usr/local/lib/python3.7/site-packages/bs4/__init__.py", line 245, in __init__
    % ",".join(features))bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

Followed the instructions [here](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser) and did a quick `pip3 install lxml` / `pip3 install html5lib` and it started processing images just fine
<img width="1084" alt="Screenshot 2020-06-24 at 14 41 49" src="https://user-images.githubusercontent.com/31315616/85558234-d7947800-b628-11ea-869d-2a3db704d9e3.png">

**Comment by Destaq** [comment]
@gbakes Thank you for letting me know, you did everything correctly.

When I had reuploaded the code I missed writing a colon. Instead of `images[i][-3:]` I had `images[i][-3]`.

If you redownload the repository or change that in the file, your code will work.
