### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by gbakes** [Destaq/reddit-wallpapers#2]
After processing all the images I do get this one error:

```
Writing image 1 of 90.Traceback (most recent call last):
  File "add_images.py", line 66, in <module>
    os.stat(f"image_{i+1}.{images[i][-3]}").st_size < 200000
FileNotFoundError: [Errno 2] No such file or directory: 'image_1.p'
```

and the scripts stops with only one image in the directory.

**Comment by Destaq** [comment]
@gbakes Please look at the previous issue. I missed writing a semicolon in the code, that has been updated now and it works.

Essentially, either redownload the repo or edit your `add_images.py` file so that it has `images[i][-3:]` in both instances. Thank you.

**Comment by Destaq** [comment]
Please confirm that this is working for you once you have changed it.

**Comment by gbakes** [comment]
Sorry didn't see the previous issue comment before submitting this ^^ didn't think you'd be that fast! Nice work 💯

**Comment by Destaq** [comment]
No problem. @gbakes Is it all good now? Sorry about the inconvenience, I had changed the code via web browser and not via IDE and so hadn't double-checked before committing. It's good that it was caught so quickly, this could have discouraged other people - thanks!

**Comment by gbakes** [comment]
Works like a charm!
